### ISSUE TITLE
solc on linux is dynamically linked

### ISSUE THREAD

**Issue by tbocek** [ether-camp/solcJ#10]
The resulting binary should work on any Linux platform, and should look as follows:
$ file solc soltest
solc: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
soltest: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped

However, the current file looks as follows:
$ file solc                                        
solc: ELF 64-bit LSB pie executable x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, stripped

That means it does not run where libmusl is not installed.

When running the build script run.sh, the following output shows the problem:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    STATIC_LINKING
```

**Comment by mkalinin** [comment]
Good point @tbocek. Latest version I guess?

**Comment by tbocek** [comment]
@mkalinin Yes, latest version. I tried to replace STATIC_LINKING with SOLC_LINK_STATIC in the dockerfile, but its still dynamically linked.

**Comment by mkalinin** [comment]
@tbocek could you make a fix for that?

**Comment by mkalinin** [comment]
Or even better to make a build for `0.4.24` version of solc

**Comment by tbocek** [comment]
@mkalinin I started to work on that, and I'm wondering why not just take the libraries from https://github.com/ethereum/solidity/releases. Was there a reason to not use those?

**Comment by mkalinin** [comment]
@tbocek great! 👍  There was no reason for that. I am pretty sure those libs will work. But previous update wasn't done by our team and I just can't say why updater hasn't used libs from solc release.

**Comment by tbocek** [comment]
@mkalinin alright! I did  some changes here: https://github.com/tbocek/solcJ/
The only issues I have are the mac binaries. Since I don't have a mac, I could not compile them and had to ask a friend to do so. The binary seems huge (17MB), and its not a sustainable approach. Do you know if there is a reliable source for mac binaries for solc?

**Comment by mkalinin** [comment]
I believe he can install it using this guide https://solidity.readthedocs.io/en/latest/installing-solidity.html#binary-packages and get installed binaries

**Comment by tbocek** [comment]
We will try, if we also get a huge binary, we'll go with that one.

**Comment by mkalinin** [comment]
Addressed in https://github.com/ether-camp/solcJ/pull/12
