### ISSUE TITLE
Maven can not resolve solcJ-all deprndency

### ISSUE THREAD

**Issue by alinaT95** [ether-camp/solcJ#11]
Hi! I'm unabe to add 

<dependency>
    <groupId>org.ethereum</groupId>
    <artifactId>solcJ-all</artifactId>
    <version>0.4.23</version>
</dependency>

into my maven project. 

Maven fails wilth the following message:

Failed to execute goal on project h: Could not resolve dependencies for project gg:h:jar:1.0-SNAPSHOT: Failure to find org.ethereum:solcJ-all:pom:0.4.23 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced.

The same issue happens for all other versions of solcJ https://mvnrepository.com/artifact/org.ethereum/solcJ-all.

Regards.

**Comment by tbocek** [comment]
Its not on https://repo.maven.apache.org/maven2, its on https://bintray.com/ethereum/maven/org.ethereum.solcJ-all/

That means you need to add:

```
<repositories>
		<repository>
			<id>my-id</id>
			<url>https://bintray.com/ethereum/maven/org.ethereum.solcJ-all</url>
		</repository>
</repositories>
```

**Comment by alinaT95** [comment]
Thank you very much! It helped.
