### ISSUE TITLE
solc on Mac

### ISSUE THREAD

**Issue by tbocek** [ether-camp/solcJ#13]
Both 0.4.23 and 0.4.24 not working for me on Mac, while 0.4.19 is ok
When compiling something, stdout and stderr both are empty, while exit code is 132 #12 

See: https://github.com/ether-camp/solcJ/pull/12

**Comment by tbocek** [comment]
should be fixed with #15

**Comment by mkalinin** [comment]
https://github.com/ether-camp/solcJ/pull/16 also has the fix
