### ISSUE TITLE
Documentation not clear

### ISSUE THREAD

**Issue by amitabh123** [ether-camp/solcJ#2]
For linux,  the instructions are:

Open file `Dockerfile` and change version to checkout Run docker service Remove prev image.

This does not make much sense. My `DockerFile` is shown below:

	FROM alpine

	RUN apk --no-cache --update add build-base cmake boost-dev git file

	# stop boost complaining about sys/poll.h
	RUN sed -i -E -e 's/include <sys\/poll.h>/include <poll.h>/' /usr/include/boost/asio/detail/socket_types.hpp

	WORKDIR /src

	RUN git clone https://github.com/open-source-parsers/jsoncpp.git
	RUN git clone --recursive https://github.com/ethereum/solidity

	# alpine has jsoncpp-dev, but it doesn't provide static libs
	RUN cd jsoncpp \
	 && cmake -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF . \
	 && make jsoncpp_lib_static \
	 && make install

	WORKDIR /src/solidity/build

	RUN git pull
	RUN git checkout v0.4.8

	# don't use nightly versioning for releases
	RUN echo -n > ../prerelease.txt

	RUN cmake -DCMAKE_BUILD_TYPE=Release \
		  -DTESTS=1 \
		  -DSTATIC_LINKING=1 \
		  ..

	RUN make --jobs=2 solc soltest

	RUN install -s solc/solc /usr/local/bin
	RUN install -s test/soltest /usr/local/bin

	RUN file /usr/local/bin/solc /usr/local/bin/soltest
	RUN du -h /usr/local/bin/solc /usr/local/bin/soltest

	RUN /usr/local/bin/solc --version

What exactly do I change? Can you put sample of "before" and "after" the change?

**Comment by cupuyc** [comment]
@amitabh123 I don't think this repo is useful for anybody, except our team. README is more internal instructions for myself, how I have built static binaries for each platform.

You can find ready to use binaries from https://github.com/ether-camp/solcJ/tree/master/src/main/resources/native

Final jar for using in java located here https://bintray.com/ethereum/maven/org.ethereum.solcJ-all/0.4.8

**Comment by amitabh123** [comment]
@cupuyc Thanks for response. I'll see if I can get the binaries to work. I am looking for a pure Java implementation of Solc, so the jar will be helpful. Are there any code samples for using the jar?

**Comment by cupuyc** [comment]
Updated readme.

Usage is not trivial, as we also use bunch of wrapper classes from ethereumJ. But at the end, you could interact with solc in Java project.
