### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by MicahZoltu** [ether-camp/solcJ#3]
Solc is up to 0.4.16 and this library's latest release in GitHub is 0.4.7 and the latest release in Bintray is 0.4.10.  Is it possible to bump to cut a release with a simple PR, or does effort need to be put into porting something forward?

**Comment by cupuyc** [comment]
Need to find/build executables for 3 platforms as per `instructions.md`.

**Comment by mkalinin** [comment]
Updated to [0.4.19](https://dl.bintray.com/ethereum/maven/org/ethereum/solcJ-all/0.4.19/)
