### ISSUE TITLE
Version 0.4.19 not yet available from the artifact repository

### ISSUE THREAD

**Issue by tglaeser** [ether-camp/solcJ#8]
Please publish version `0.4.19` of module `org.ethereum:solcJ-all` to the artifact repository. Thanks!

**Comment by tglaeser** [comment]
@mkalinin @romanman I see that you guys have access to the [ethereum repository](https://bintray.com/ethereum); what's holding you back publishing this artifact?

**Comment by mkalinin** [comment]
Sorry for delay, it's there: [0.4.19](https://dl.bintray.com/ethereum/maven/org/ethereum/solcJ-all/0.4.19/)
